#!/bin/sh
# autogen.sh

ACLOCAL_FLAGS=
GETTEXTIZE_FLAGS=-c
# LIBTOOLIZE_FLAGS=-c
AUTOCONF_FLAGS=
AUTOMAKE_FLAGS="-a -c --gnu"

test -r configure.in || exit 1

if [ "$1" == "--clean" ]
then
	echo -n "Cleaning out autogenerated files..."

	test -r Makefile && make distclean

	find . -type f -name Makefile.in -exec rm -f {} \;

	rm -f \
		ABOUT-NLS \
		aclocal.m4 \
		config.cache \
		config.h \
		config.h.in \
		config.log \
		config.status \
		configure \
		libtool \
		stamp-h \
		stamp-h.in \
		po/Makefile.in.in

	rm -rf config intl

	echo "done."
	exit 0
fi

echo "Running 'aclocal $ACLOCAL_FLAGS'"
aclocal $ACLOCAL_FLAGS || exit 1

if [ ! -f config.h.in ]
then
	echo "Running 'autoheader'"
	autoheader || exit 1
fi

mkdir -p config

echo "Running 'gettextize $GETTEXTIZE_FLAGS'"
gettextize $GETTEXTIZE_FLAGS || exit 1
rm -f intl/*
touch intl/Makefile.am

# echo "Running 'libtoolize $LIBTOOLIZE_FLAGS'"
# libtoolize $LIBTOOLIZE_FLAGS || exit 1

echo "Running 'autoconf $AUTOCONF_FLAGS'"
autoconf $AUTOCONF_FLAGS || exit 1

echo "Running 'automake $AUTOMAKE_FLAGS'"
automake $AUTOMAKE_FLAGS || exit 1

echo "Running 'configure $@'"
./configure "$@" && (echo ; echo "Now type 'make' to compile.")

# end autogen.sh
